### ISSUE TITLE
Can't clock into job

### ISSUE THREAD

**Issue by eMaurine** [gullidog/Royalty#13]
**Describe the bug**
When I press F6 to clock in or out of job it only shows part of the screen 

**How to Reproduce the Behavior**
Steps to reproduce the behaviour:

**Expected Behaviour**
Press F6 to clock in or off jobs 

**Screenshots**
![jobclock](https://user-images.githubusercontent.com/89552668/130871042-60837536-d9a0-4a8a-bf11-3dd19c937311.png)
![image](https://user-images.githubusercontent.com/89552668/130871566-354fb3c5-7175-462c-9832-26cce662f1b0.png)

**Additional context**

**Comment by Droshky** [comment]
What resolution are you on?

**Comment by eMaurine** [comment]
[image: image.png]

**Comment by eMaurine** [comment]
![image](https://user-images.githubusercontent.com/89552668/132639117-2b095689-5569-402c-ab5e-a9f5b4d2e924.png)

**Comment by eMaurine** [comment]
![image](https://user-images.githubusercontent.com/89552668/132971102-611ce924-5470-4be3-8961-e6681212bc30.png)

**Comment by Droshky** [comment]
ok thank you, ill look into making the job menu available for all resolution sizes
