### ISSUE TITLE
Cant sell drugs after a while

### ISSUE THREAD

**Issue by Taughthalo** [gullidog/Royalty#16]
After a while of selling drugs, it seems that it does not automatically stop your selling after you start running. It happens randomly but it seems to happen most after someone steals your drugs. Once the red notice stops popping up after moving too much, you can start and stop the selling but no customers will come to you for an offer and the only way to fix it is to leave and come back into the city.

**Comment by gullidog** [comment]
We are aware of the current bugs of the corner selling and are in the process of writing a new one!

Thank you for your report!
**_Brad_**
