### ISSUE TITLE
Vehicle Cleaning Bug

### ISSUE THREAD

**Issue by JooniJunebug** [gullidog/Royalty#20]
**Describe the bug**
Whenever you clean a vehicle your hat/glasses get removed and the rag gets stuck in your hand and you must /refreshskin.

**How to Reproduce the Behavior**
Clean a Vehicle

**Additional context**
please lmk if you need any other info.

**Comment by Droshky** [comment]
looking into this

**Comment by gullidog** [comment]
Will be fixed on restart! Thank you for your report!

**_Brad_**
