### ISSUE TITLE
Radio / Normal Voice weirdness with Phone

### ISSUE THREAD

**Issue by Khadbtv** [gullidog/Royalty#5]
**Describe the bug**
It seems that if you are on PD radio, and get a phone call, using the normal voice does not broadcast over the phone. However, if you use the radio instead, it broadcasts to both the phone AND PD radio.

If you aren't on a radio at all, then the phone does work with the normal voice as intended.

**How to Reproduce the Behavior**
Get on Radio PD, then call someone. Try to use Normal voice to talk - the person on the phone can't hear you. Then use radio voice to talk, both PD and the phone will hear you.

**Expected Behaviour**
That you can use the normal voice to talk on the phone regardless of being on PD radio.

**Comment by gullidog** [comment]
Unfortunately we are aware of current bugs with the mumble-voip we implemented. We are currently in the progress of trying to implement new methods that take advantage of NativeAudio. Apologies for any inconveniences while we research and implement new methods. Thank you for your report!
