### ISSUE TITLE
Pulled me car out to discover an issue

### ISSUE THREAD

**Issue by Rownin** [gullidog/Royalty#7]
**Describe the bug**
The default stance on my car seems to be rather wacky

**How to Reproduce the Behavior**
Literally car was like this after pulling out of garage, different garages have no marked effect

**Expected Behavior**
I have never stanced my vehicle

**Screenshots**
https://gyazo.com/28bd72b28b6a154da93f9d7ef64e5b07
https://gyazo.com/95bb241c992313a635cf70cead08cd87

**Additional context**
Happened after this most recent tsunami

**Comment by gullidog** [comment]
Apologies for these issues, is this still randomly happening or is it fixed now. It should be fixed but please let me know otherwise! Thank you for the bug report!

**_Brad_**

**Comment by Rownin** [comment]
Seems to be fixed, thank you.
